#Enable No Startup Messages module
noStartupMessagesEnabled = true
#A list of word sequences that if contained in a message will be stopped.
noStartupMessagesMessages = ["Ender IO is in alpha - expect bugs and take backups often!", "Warning: Mekanism is currently in alpha, and is not recommended for widespread use in modpacks."]
#Disable recipe advancements
disableRecipeAdvancements = true
#Enable startup ding sound
enableDingDongStartupSound = true
#Name of sound to play. Default is entity.experience_orb.pickup
dingDongSound = "entity.experience_orb.pickup"
