//
priority:
1000

global["unUnified"] = [
'stellaris:steel_block',
'stellaris:steel_ingot', 
'stellaris:steel_nugget', 
'stellaris:uranium_block',
'stellaris:uranium_ingot',
'railcraft:coal_dust',
'railcraft:ender_dust',
'railcraft:lead_nugget', 
'railcraft:bronze_block', 
'railcraft:lead_ore', 
'railcraft:lead_block', 
'railcraft:tin_ore', 
'railcraft:tin_block', 
'railcraft:bronze_ingot', 
'railcraft:deepslate_lead_ore', 
'railcraft:lead_raw', 
'railcraft:deepslate_tin_ore', 
'railcraft:tin_raw', 
'railcraft:bronze_nugget', 
'railcraft:lead_nugget', 
'railcraft:lead_ingot', 
'railcraft:tin_nugget', 
'railcraft:tin_ingot',
'occultism:gold_dust', 
'railcraft:bronze_block',
'railcraft:obsidian_dust',
'occultism:obsidian_dust',
'appflux:diamond_dust',
'railcraft:silver_block',
'xycraft_machines:gold_sheet',
'occultism:copper_dust',
'appflux:emerald_dust',
'xycraft_machines:copper_sheet',
'railcraft:lead_ingot',
'xycraft_machines:iron_sheet',
'railcraft:charcoal_dust',
'railcraft:deepslate_tin_ore', 
'railcraft:tin_ore',
'railcraft:lead_block',
'railcraft:silver_nugget',
'railcraft:tin_nugget',
'railcraft:lead_raw',
'railcraft:bronze_nugget',
'railcraft:lead_nugget',
'railcraft:tin_ingot',
'railcraft:silver_ingot',
'railcraft:sulfur_dust',
'railcraft:tin_raw',
'railcraft:bronze_ingot',
'railcraft:deepslate_silver_ore', 
'railcraft:silver_ore',
'occultism:iron_dust', 
'railcraft:tin_block',
'railcraft:deepslate_lead_ore', 
'railcraft:lead_ore',
'railcraft:silver_raw',
// Commenting here as Steel from Railcraft may be obtained through Villager Trading.
// 'railcraft:steel_block', 
// 'railcraft:steel_ingot',
// 'railcraft:steel_nugget',
"xycraft_machines:resin_block",
"xycraft_machines:resin_ball",
'oritech:raw_nickel',
// 'railcraft:steel_shovel',
// 'railcraft:steel_pickaxe',
// 'railcraft:steel_axe',
// 'railcraft:steel_hoe',
// 'railcraft:steel_sword',
'railcraft:steel_helmet',
'railcraft:steel_chestplate',
'railcraft:steel_leggings',
'railcraft:steel_boots',
'stellaris:steel_sword', 
'stellaris:steel_hoe', 
'stellaris:steel_pickaxe', 
'stellaris:steel_shovel', 
'stellaris:steel_axe',
"create:brass_block",
"create:brass_ingot",
"create:brass_nugget",
"create:brass_sheet",
"create:zinc_block",
"create:zinc_ingot",
"create:zinc_nugget",
"create:raw_zinc",
"create:copper_sheet",
"create:copper_nugget",
"create:golden_sheet",
"create:iron_sheet",
"create:powdered_obsidian",
"create:wheat_flour",
"enderio:flour",
"refinedstorage:silicon",
"enderio:silicon",
"oritech:silicon",
"oritech:silicon_block"
];